name = "Bingomatic"
uuid = "5d0f211d-823e-4d77-a844-586f1e6d1e5a"
authors = ["itsdfish <itsdfish@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"
Plots = "v1.9.1"
PyPlot = "v2.9.0"
SafeTestsets = "v0.0.1"
StatsBase = "v0.33.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
